name: Xcode Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Taurus
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build
        run: |
          xcodebuild \
            -project Taurus.xcodeproj \
            -target Taurus \
            -configuration Release \
            build
